from .combat.combat import OSRSCombat
from .woodcutter import OSRSWoodcutter
from .fletching import OSRSBankFletcher
from .wintertoad import OSRSwintertoad
from .Miner import OSRSMiner
from .rooftops import OSRSAgility
from .ardyknights import OSRSTheiving
from .motherlode import OSRSMotherLode
from .blast import OSRSBlast
from .cannonballs import OSRSCannonballs
from .buyyer import OSRSBuyIronOre
from .superglass import OSRSsuperglass
from .gotr import OSRSGOTR
from .make_glass import OSRScraftmolten
from .string import OSRSbowstring
from .barb_fishing import OSRSBarbFisher
from .karambwan_fishing import OSRSKarambwan
from .herblore import OSRSMakepot
from .amythis import OSRSAmethesMiner
from .cooking import OSRSCooker
from .plankMake import OSRSplankMake
from .fire_making import OSRSfireMake
from .slayer import OSRSSlayer
from .NMZ import OSRSNMZ
